# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            DOYOUREALLYWANTTOHURT.ME
tagline:          'by Michael Tomko'
description:      'Real talk from a husband and soon-to-be-father who is just trying to keep his head above water.<br><a href="http://twitter.com/michaeltomko" target="_blank">@michaeltomko</a>'
url:              http://doyoureallywanttohurt.me

author:
  name:           'Michael Tomko'
  url:            https://twitter.com/michaeltomko

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
